# Generated by Django 5.2.7 on 2025-12-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cml', '0003_add_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
