# Generated by Django 5.2.7 on 2025-11-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_category_exclude_from_menu_category_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=36, unique=True),
        ),
    ]
