# Generated by Django 5.2.7 on 2025-12-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_productclass_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategoryHierarchy',
        ),
        migrations.RemoveField(
            model_name='category',
            name='exclude_from_menu',
        ),
        migrations.RemoveField(
            model_name='category',
            name='long_description',
        ),
    ]
