# Generated by Django 5.2.7 on 2025-12-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_productcategoryhierarchy_category_exclude_from_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productclass',
            old_name='code',
            new_name='c1_uid',
        ),
        migrations.AddField(
            model_name='product',
            name='c1_uid',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=36, unique=True),
        ),
    ]
