# Generated by Django 5.2.7 on 2025-12-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_rename_code_productclass_c1_uid_product_c1_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c1_uid',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=36, unique=True),
        ),
    ]
